import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://platform.linkedin.com/badges/js/profile.js"
          async
          defer
          type="text/javascript"
        ></script>
      </Head>

      <main className="container bg-black mx-auto">
        <div
          className="badge-base LI-profile-badge"
          data-locale="tr_TR"
          data-size="medium"
          data-theme="light"
          data-type="VERTICAL"
          data-vanity="mucahitkok"
          data-version="v1"
        >
          <a
            className="badge-base__link LI-simple-link"
            href="https://tr.linkedin.com/in/mucahitkok?trk=profile-badge"
          ></a>
        </div>
      </main>
    </div>
  );
}
